use super::config::*;
use crate::input::manager::InputState;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

/// A scalar command the input mapper produced for the WS client.
/// Either a raw ROS topic/channel write (legacy) or a WS-input write
/// (new path). The runtime dispatches each variant to the matching
/// WebSocketClient method.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum MappedCommand {
    Topic {
        topic: String,
        channel: String,
        value: Value,
    },
    WsInput {
        sheet_id: String,
        input_id: String,
        value: Value,
    },
}

impl MappedCommand {
    fn from_target(target: &super::config::ControlTarget, value: Value) -> Self {
        match target {
            super::config::ControlTarget::Topic { topic, channel, .. } =>
                MappedCommand::Topic {
                    topic: topic.clone(),
                    channel: channel.clone(),
                    value,
                },
            super::config::ControlTarget::WsInput { sheet_id, input_id, .. } =>
                MappedCommand::WsInput {
                    sheet_id: sheet_id.clone(),
                    input_id: input_id.clone(),
                    value,
                },
        }
    }

}

/// Action events generated by input processing
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ActionEvent {
    /// Send a control command
    Command(MappedCommand),
    /// Show a preset panel
    ShowPanel { panel_id: String },
    /// Hide the current panel
    HidePanel,
    /// Navigate within a panel
    NavigatePanel { direction: NavigateDirection },
    /// Select the current panel item
    SelectPanelItem,
    /// Activate a specific preset
    ActivatePreset { preset_id: String },
    /// Fire one item on a board. The frontend routes it by the board's
    /// kind (start_animation / apply_pose / play_sound) — the same path
    /// selecting the item in the panel overlay takes.
    ActivateBoardItem { panel_id: String, item_id: String },
    /// Toggle an output
    ToggleOutput { target_id: String },
    /// Cycle through output values
    CycleOutput { target_id: String, value: String },
    /// Emergency stop
    EStop,
}

/// Panel navigation state
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PanelState {
    pub active_panel_id: Option<String>,
    pub selected_index: usize,
    pub current_page: usize,
}

/// Saved profiles structure for persistence
#[derive(Debug, Clone, Serialize, Deserialize)]
struct SavedProfiles {
    profiles: Vec<BindingProfile>,
    active_profile_id: String,
}

/// Maps input state to commands and actions based on bindings
pub struct InputMapper {
    profiles: Vec<BindingProfile>,
    active_profile_id: String,
    last_analog_values: HashMap<String, f32>,
    /// Wall-clock of the last send per analog key. Drives the heartbeat
    /// re-send so a dropped dead-stick packet doesn't permanently strand
    /// the motor — every `HEARTBEAT_MS` we re-emit the current value
    /// regardless of change detection.
    last_send_times: HashMap<String, std::time::Instant>,
    last_button_states: HashMap<String, bool>,
    panel_state: PanelState,
    cycle_indices: HashMap<String, usize>,
    toggle_states: HashMap<String, bool>,
    modifier_values: HashMap<String, f32>,
}

/// Force re-send each analog target this often even if change detection
/// says nothing new — protects against dropped dead-stick (return-to-zero)
/// packets, post-reconnect drift, and the firmware coming back from a
/// brown-out reset while the operator's hands are off the stick.
/// Re-assert cadence for an unchanged bound value.
///
/// This is not just a controller-local backstop — it sets the cadence of
/// the whole downstream liveness chain, because the server's motor
/// re-assert is REACTIVE, not timer-driven. routing_evaluator's
/// `_dispatch_sink` only re-asserts an unchanged non-neutral motor value
/// when an evaluation happens, and an evaluation happens when WE push.
/// So the period the firmware actually sees is:
///
/// ```text
/// ceil(_MOTOR_REASSERT_MS / HEARTBEAT_MS) * HEARTBEAT_MS
/// ```
///
/// against `ROBOCLAW_DEADMAN_MS` = 1250 ms, which zeroes a running motor
/// when setpoints stop arriving. /control is BEST_EFFORT DDS, so packets
/// genuinely drop there (unlike our own WS leg, which is TCP — that
/// either delivers or drops the connection).
///
/// ```text
/// push    firmware sees   consecutive /control losses survived
/// 500 ms  500 ms          1
/// 250 ms  500 ms          1     <- ceil() makes 250 no better than 500
/// 150 ms  300 ms          3
/// ```
///
/// 500 ms is what the firmware comment calls "tolerate one lost
/// re-assert" — the designed minimum. But before the value_active
/// re-emit was removed, a held stick pushed at the 20 ms throttle rate,
/// so the firmware really saw 300 ms and survived three losses. Dropping
/// to 500 ms would have quietly traded that margin away: two dropped
/// /control frames while holding throttle and the dead-man fires,
/// cutting the motor until the next re-assert. Fail-safe, but a visible
/// stutter on a lossy link.
///
/// 150 ms restores the 300 ms the firmware used to see while still
/// costing ~7 messages/sec for a static axis instead of 50.
const HEARTBEAT_MS: u64 = 150;

/// Gyro full-scale, deg/s. Mirrors GYRO_SCALE in input/steamdeck_hid.rs
/// (raw counts * 2000/32768), so an axis saturates at +/-2000. Used to
/// bring IMU rates into the -1..1 range every other analog input uses.
const GYRO_FULL_SCALE_DPS: f32 = 2000.0;

/// Angular rate (deg/s) -> -1..1, saturating at full scale.
fn normalize_gyro(dps: f32) -> f32 {
    (dps / GYRO_FULL_SCALE_DPS).clamp(-1.0, 1.0)
}

/// A trackpad axis is only input while the pad is touched. Releasing a
/// pad is a return to neutral, exactly like releasing a stick — see the
/// note in get_analog_value.
fn touch_axis(touched: bool, position: f32) -> f32 {
    if touched { position } else { 0.0 }
}

impl InputMapper {
    pub fn new() -> Self {
        // Try to load profiles from disk, fall back to defaults
        let (profiles, active_profile_id) = Self::load_profiles_from_disk()
            .unwrap_or_else(|| {
                log::info!("No saved profiles found, using defaults");
                (vec![super::presets::create_default_profile()], "default".to_string())
            });

        Self {
            profiles,
            active_profile_id,
            last_analog_values: HashMap::new(),
            last_send_times: HashMap::new(),
            last_button_states: HashMap::new(),
            panel_state: PanelState::default(),
            cycle_indices: HashMap::new(),
            toggle_states: HashMap::new(),
            modifier_values: HashMap::new(),
        }
    }

    /// Get the profiles config file path
    fn get_profiles_path() -> Option<PathBuf> {
        dirs::data_dir().map(|p| p.join("com.saintos.controller").join("profiles.json"))
    }

    /// Load profiles from disk
    fn load_profiles_from_disk() -> Option<(Vec<BindingProfile>, String)> {
        let path = Self::get_profiles_path()?;
        if !path.exists() {
            return None;
        }

        let content = fs::read_to_string(&path).ok()?;
        let saved: SavedProfiles = serde_json::from_str(&content).ok()?;
        log::info!("Loaded {} profiles from {:?}", saved.profiles.len(), path);
        Some((saved.profiles, saved.active_profile_id))
    }

    /// Save profiles to disk
    pub fn save_profiles_to_disk(&self) {
        if let Some(path) = Self::get_profiles_path() {
            // Ensure directory exists
            if let Some(parent) = path.parent() {
                let _ = fs::create_dir_all(parent);
            }

            let saved = SavedProfiles {
                profiles: self.profiles.clone(),
                active_profile_id: self.active_profile_id.clone(),
            };

            match serde_json::to_string_pretty(&saved) {
                Ok(json) => {
                    if let Err(e) = fs::write(&path, json) {
                        log::error!("Failed to save profiles to {:?}: {}", path, e);
                    } else {
                        log::info!("Saved {} profiles to {:?}", self.profiles.len(), path);
                    }
                }
                Err(e) => {
                    log::error!("Failed to serialize profiles: {}", e);
                }
            }
        }
    }

    pub fn get_profiles(&self) -> &[BindingProfile] {
        &self.profiles
    }

    pub fn set_profiles(&mut self, profiles: Vec<BindingProfile>) {
        self.profiles = profiles;
        if !self.profiles.iter().any(|p| p.id == self.active_profile_id) {
            self.active_profile_id = self
                .profiles
                .first()
                .map(|p| p.id.clone())
                .unwrap_or_default();
        }
        // Persist to disk
        self.save_profiles_to_disk();
    }

    pub fn set_active_profile(&mut self, profile_id: &str) {
        if self.profiles.iter().any(|p| p.id == profile_id) {
            self.active_profile_id = profile_id.to_string();
            // Persist to disk
            self.save_profiles_to_disk();
        }
    }

    pub fn active_profile(&self) -> Option<&BindingProfile> {
        self.profiles
            .iter()
            .find(|p| p.id == self.active_profile_id)
    }

    #[allow(dead_code)] // panel state is owned/driven from the frontend today
    pub fn panel_state(&self) -> &PanelState {
        &self.panel_state
    }

    /// Process input state and generate action events
    pub fn process(&mut self, input: &InputState) -> Vec<ActionEvent> {
        // Move the profiles Vec out of `self` so the active profile can
        // be borrowed immutably while process_*_bindings hold &mut self
        // (for the change-detection caches). This replaces a full
        // BindingProfile CLONE on every 60 Hz frame — the profile carries
        // Vecs of analog + digital bindings, panels, and presets, so that
        // clone dominated the per-frame cost (~5.5 µs). mem::take swaps in
        // an empty Vec (cheap) and we restore it before returning; the
        // binding helpers never read self.profiles, so the temporarily-
        // empty Vec is never observed.
        let profiles = std::mem::take(&mut self.profiles);
        let mut events = Vec::new();
        if let Some(idx) = profiles.iter().position(|p| p.id == self.active_profile_id) {
            let profile = &profiles[idx];
            self.process_analog_bindings(profile, input, &mut events);
            self.process_digital_bindings(profile, input, &mut events);
        }
        self.profiles = profiles; // restore
        events
    }

    /// Whether the ACTIVE profile has an enabled binding driven by the
    /// IMU. This is the demand signal that decides whether the sensor
    /// gets powered at all (see InputManager::set_gyro_binding_demand) —
    /// the Steam Deck's IMU costs battery whenever it's streaming, and
    /// before this it ran unconditionally for the app's whole lifetime.
    ///
    /// Deliberately ignores which ACTION the binding carries. A gyro
    /// axis wired to DifferentialDrive is a no-op in
    /// process_analog_bindings, but treating that as "no demand" would
    /// mean an operator staring at a gyro binding they configured while
    /// the sensor silently stays off. Over-reporting costs idle power;
    /// under-reporting costs a control that doesn't work.
    pub fn uses_gyro(&self) -> bool {
        self.profiles
            .iter()
            .find(|p| p.id == self.active_profile_id)
            .is_some_and(|p| {
                p.analog_bindings.iter().any(|b| {
                    b.enabled
                        && matches!(
                            b.input,
                            AnalogInput::GyroPitch
                                | AnalogInput::GyroRoll
                                | AnalogInput::GyroYaw
                        )
                })
            })
    }

    /// Command neutral on every analog target the active profile drives,
    /// and forget the send records so the next `process()` tick
    /// re-asserts from live input.
    ///
    /// Called when the app stops being the focused window. Simply
    /// pausing the input loop there is not safe: a deflected stick has
    /// already been commanded, the server change-gates unchanged values,
    /// and the only thing that would eventually stop the motor is the
    /// firmware dead-man at ROBOCLAW_DEADMAN_MS (1250 ms). At full
    /// throttle that is metres of travel after the operator's attention
    /// left the screen. So we say zero explicitly, and rely on the
    /// dead-man only as the backstop it was meant to be.
    ///
    /// Deliberately analog-only. Running the whole `process()` path
    /// against a synthetic neutral InputState would produce these same
    /// zeros, but it would also present every button as released and
    /// fire any `ButtonTrigger::Release` binding — a spurious action
    /// triggered by the operator opening the Steam overlay.
    ///
    /// The emitted zeros are stop values, so they bypass the client's
    /// per-target throttle and are exempt from its e-stop gate: they go
    /// out now, not on the next window.
    pub fn release_all_analog(&mut self) -> Vec<ActionEvent> {
        let mut events = Vec::new();
        let zero = Value::from(0.0);

        if let Some(profile) = self.profiles.iter().find(|p| p.id == self.active_profile_id) {
            for binding in &profile.analog_bindings {
                if !binding.enabled {
                    continue;
                }
                match &binding.action {
                    AnalogAction::DirectControl { target, .. } => {
                        events.push(ActionEvent::Command(MappedCommand::from_target(
                            target,
                            zero.clone(),
                        )));
                    }
                    AnalogAction::DifferentialDrive {
                        topic,
                        left_channel,
                        right_channel,
                        ..
                    } => {
                        // Both tracks, or the un-zeroed one keeps running.
                        for channel in [left_channel, right_channel] {
                            events.push(ActionEvent::Command(MappedCommand::Topic {
                                topic: topic.clone(),
                                channel: channel.clone(),
                                value: zero.clone(),
                            }));
                        }
                    }
                    // Modifiers scale other bindings; they command nothing
                    // of their own, so there is nothing to neutralize.
                    AnalogAction::Modifier { .. } => {}
                }
            }
        }

        // Whatever we thought was on the wire is now superseded by these
        // zeros, and on refocus every axis must re-assert from live input.
        self.forget_all_sends();
        events
    }

    /// Forget every send record, so the next `process()` tick re-asserts
    /// the current value of every bound axis — deflections and zeros
    /// alike.
    ///
    /// Called when a link comes up. Nothing the mapper "sent" while
    /// disconnected actually reached a server, so its bookkeeping is a
    /// record of a conversation that never happened; left in place, a
    /// freshly connected server would be told nothing about an axis
    /// until it next moved or the 500 ms heartbeat came round.
    pub fn forget_all_sends(&mut self) {
        self.last_analog_values.clear();
        self.last_send_times.clear();
    }

    /// Forget that `cmd` was ever sent, so the next `process()` tick
    /// re-detects it as unsent and re-emits it.
    ///
    /// The analog paths below commit `last_analog_values` /
    /// `last_send_times` at the moment they QUEUE a command — before
    /// the WS client has had a chance to accept it. That's an
    /// optimistic write: if the client then refuses the value (link
    /// down, stream token queue saturated), the mapper still believes
    /// it was delivered and the change-detection logic goes quiet. For
    /// a deflection that's harmless — the next stick movement re-sends.
    /// For a RETURN TO ZERO it is not: the stop is the last thing the
    /// mapper will ever say about that channel, so a refused stop left
    /// the motor running at the previously-commanded velocity until the
    /// 500 ms heartbeat came around.
    ///
    /// Calling this on a failed send drops the bookkeeping so the retry
    /// happens on the next tick (INPUT_LOOP_MS, ~4 ms) instead.
    pub fn note_send_failed(&mut self, cmd: &MappedCommand) {
        // Key shapes this has to match, all built in the analog paths:
        //   DirectControl      "<Input>::topic::<topic>::<channel>"
        //                      "<Input>::ws::<sheet>::<input>"
        //   DifferentialDrive  "<topic>::<channel>"   (bare, no prefix)
        // A target can be driven by more than one input, so clear every
        // entry that resolves to it — over-clearing only costs one
        // redundant re-send, under-clearing strands a motor.
        let (suffix, topic_prefix) = match cmd {
            MappedCommand::Topic { topic, channel, .. } => (
                format!("topic::{}::{}", topic, channel),
                // Differential drive keys the pair on bare topic::channel
                // and heartbeats the pair off the LEFT slot alone, so
                // clearing just the failed channel can leave the pair's
                // timer intact. Clear every slot on this topic instead.
                Some(format!("{}::", topic)),
            ),
            MappedCommand::WsInput { sheet_id, input_id, .. } => (
                format!("ws::{}::{}", sheet_id, input_id),
                None,
            ),
        };

        let stale = |k: &str| {
            k.ends_with(&suffix)
                || topic_prefix.as_deref().is_some_and(|p| k.starts_with(p))
        };

        self.last_analog_values.retain(|k, _| !stale(k));
        self.last_send_times.retain(|k, _| !stale(k));
    }

    fn process_analog_bindings(
        &mut self,
        profile: &BindingProfile,
        input: &InputState,
        events: &mut Vec<ActionEvent>,
    ) {
        for binding in &profile.analog_bindings {
            if !binding.enabled {
                continue;
            }

            let raw_value = self.get_analog_value(input, &binding.input);

            match &binding.action {
                AnalogAction::DirectControl { target, transform } => {
                    let transformed = transform.apply(raw_value);

                    // Apply modifiers
                    let modified = self.apply_modifiers(transformed);

                    // Key the change-detection cache by (input, target) —
                    // not just by input. Tank-style setups bind the same
                    // gamepad axis to two targets (one per track-drive
                    // sheet), and if both share a single "LeftStickY"
                    // cache entry, the first iteration's stick-release
                    // event clobbers `last` to 0 and the second target
                    // sees no change → never sends its zero → its motor
                    // sticks at the last commanded velocity.
                    let target_key = match target {
                        super::config::ControlTarget::Topic { topic, channel, .. } =>
                            format!("topic::{}::{}", topic, channel),
                        super::config::ControlTarget::WsInput { sheet_id, input_id, .. } =>
                            format!("ws::{}::{}", sheet_id, input_id),
                    };
                    let key = format!("{:?}::{}", binding.input, target_key);
                    let last = self.last_analog_values.get(&key).copied().unwrap_or(0.0);
                    let delta = (modified - last).abs();

                    // Send command if:
                    // 1. Value changed significantly (delta > 0.001), OR
                    // 2. Value just returned to zero (send final stop command), OR
                    // 3. Heartbeat — re-assert current value periodically so a
                    //    dropped packet (Wi-Fi blip, firmware brown-out reboot,
                    //    server reconnect, etc.) can't permanently strand the
                    //    motor at a non-zero value.
                    //
                    // There used to be a fourth: re-emit whenever the value
                    // is non-zero, on every 4 ms tick. That existed to
                    // outlast the client's per-target throttle, which
                    // silently dropped a write inside its window while the
                    // mapper recorded it as sent. The throttle now reports
                    // that deferral (client.rs THROTTLED) and the input loop
                    // answers it via note_send_failed, so only the writes
                    // actually dropped get retried — instead of ~230 of
                    // every 250 emissions existing to brute-force past it.
                    //
                    // Liveness downstream does not depend on that re-emit.
                    // The chain is documented at both ends and sized around
                    // this heartbeat: the server change-gates unchanged
                    // values and re-asserts motor channels itself
                    // (routing_evaluator _MOTOR_REASSERT_MS = 300 ms,
                    // effective period max(that, heartbeat) ~= 500 ms), the
                    // firmware dead-man is ROBOCLAW_DEADMAN_MS = 1250 ms
                    // "to tolerate one lost re-assert", and the RoboClaw's
                    // own serial watchdog is fed by the firmware every
                    // ROBOCLAW_DUTY_KEEPALIVE_MS = 400 ms from its stored
                    // duty — not by us. 500 ms against 1250 ms is the margin
                    // the design already assumes.
                    let value_changed = delta > 0.001;
                    let returned_to_zero = last.abs() > 0.001 && modified.abs() <= 0.001;
                    let heartbeat_due = match self.last_send_times.get(&key) {
                        Some(t) => t.elapsed() >= std::time::Duration::from_millis(HEARTBEAT_MS),
                        None => true,
                    };
                    let should_send = value_changed || returned_to_zero || heartbeat_due;

                    if should_send {
                        self.last_analog_values.insert(key.clone(), modified);
                        self.last_send_times.insert(key, std::time::Instant::now());

                        events.push(ActionEvent::Command(MappedCommand::from_target(
                            target,
                            Value::from(modified),
                        )));
                    }
                }
                AnalogAction::DifferentialDrive {
                    topic,
                    left_channel,
                    right_channel,
                    throttle_transform,
                    turn_transform,
                } => {
                    // Get both stick axes based on which axis this binding is for
                    // DifferentialDrive should be bound to the Y axis (throttle) of a stick
                    let (throttle_raw, turn_raw) = match &binding.input {
                        AnalogInput::LeftStickY => (
                            input.gamepad.left_stick.y,
                            input.gamepad.left_stick.x,
                        ),
                        AnalogInput::RightStickY => (
                            input.gamepad.right_stick.y,
                            input.gamepad.right_stick.x,
                        ),
                        // If bound to X axis, swap the interpretation
                        AnalogInput::LeftStickX => (
                            input.gamepad.left_stick.y,
                            input.gamepad.left_stick.x,
                        ),
                        AnalogInput::RightStickX => (
                            input.gamepad.right_stick.y,
                            input.gamepad.right_stick.x,
                        ),
                        // Trackpads: throttle = y, turn = x, same as a stick
                        // (either axis of the pad selects the whole pad).
                        AnalogInput::LeftPadX | AnalogInput::LeftPadY => (
                            input.left_touchpad.y,
                            input.left_touchpad.x,
                        ),
                        AnalogInput::RightPadX | AnalogInput::RightPadY => (
                            input.right_touchpad.y,
                            input.right_touchpad.x,
                        ),
                        // Triggers don't make sense for differential drive
                        _ => continue,
                    };

                    // Apply transforms
                    let throttle = self.apply_modifiers(throttle_transform.apply(throttle_raw));
                    let turn = self.apply_modifiers(turn_transform.apply(turn_raw));

                    // Channel mixing: left = throttle + turn, right = throttle - turn
                    let mut left = throttle + turn;
                    let mut right = throttle - turn;

                    // Normalize if either exceeds bounds (proportional scaling)
                    let max_val = left.abs().max(right.abs());
                    if max_val > 1.0 {
                        left /= max_val;
                        right /= max_val;
                    }

                    // Check if we should send (same logic as DirectControl but for the combined values).
                    // Match DirectControl's heartbeat behaviour: re-emit
                    // the current values periodically so a dropped
                    // deadstick packet doesn't permanently strand the
                    // motors. Without this, a single lost UDP frame on
                    // return-to-zero leaves both tracks running at the
                    // last commanded velocity until the operator nudges
                    // the stick again.
                    let key_left = format!("{}::{}", topic, left_channel);
                    let key_right = format!("{}::{}", topic, right_channel);
                    let last_left = self.last_analog_values.get(&key_left).copied().unwrap_or(0.0);
                    let last_right = self.last_analog_values.get(&key_right).copied().unwrap_or(0.0);

                    let delta_left = (left - last_left).abs();
                    let delta_right = (right - last_right).abs();
                    let any_changed = delta_left > 0.001 || delta_right > 0.001;
                    // No any_active re-emit — same reasoning as
                    // DirectControl above.
                    let returned_to_zero = (last_left.abs() > 0.001 || last_right.abs() > 0.001)
                        && left.abs() <= 0.001 && right.abs() <= 0.001;
                    // Heartbeat is keyed on the LEFT slot but covers both —
                    // they're always sent together, so a single timer
                    // tracks the pair correctly.
                    let heartbeat_due = match self.last_send_times.get(&key_left) {
                        Some(t) => t.elapsed() >= std::time::Duration::from_millis(HEARTBEAT_MS),
                        None => true,
                    };
                    let should_send = any_changed || returned_to_zero || heartbeat_due;

                    if should_send {
                        self.last_analog_values.insert(key_left.clone(), left);
                        self.last_analog_values.insert(key_right, right);
                        let now = std::time::Instant::now();
                        self.last_send_times.insert(key_left, now);

                        // Send both left and right commands. Differential
                        // drive stays on the raw topic/channel path — the
                        // server-side routing graph is where the operator
                        // mixes individual WS inputs into tank-drive
                        // commands.
                        events.push(ActionEvent::Command(MappedCommand::Topic {
                            topic: topic.clone(),
                            channel: left_channel.clone(),
                            value: Value::from(left),
                        }));
                        events.push(ActionEvent::Command(MappedCommand::Topic {
                            topic: topic.clone(),
                            channel: right_channel.clone(),
                            value: Value::from(right),
                        }));
                    }
                }
                AnalogAction::Modifier { effect } => {
                    // Store modifier value for use by other bindings
                    match effect {
                        ModifierEffect::PrecisionMode { .. } => {
                            self.modifier_values.insert("precision".to_string(), raw_value);
                        }
                        ModifierEffect::SpeedBoost { .. } => {
                            self.modifier_values.insert("speed_boost".to_string(), raw_value);
                        }
                        ModifierEffect::ScaleTarget { target_id, .. } => {
                            self.modifier_values.insert(target_id.clone(), raw_value);
                        }
                    }
                }
            }
        }
    }

    fn process_digital_bindings(
        &mut self,
        profile: &BindingProfile,
        input: &InputState,
        events: &mut Vec<ActionEvent>,
    ) {
        for binding in &profile.digital_bindings {
            if !binding.enabled {
                continue;
            }

            let pressed = self.get_button_pressed(input, &binding.input);
            let key = format!("{:?}", binding.input);
            let was_pressed = self.last_button_states.get(&key).copied().unwrap_or(false);
            self.last_button_states.insert(key.clone(), pressed);

            // For now, handle Press trigger (TODO: implement Hold, DoubleTap, LongPress)
            let triggered = match binding.trigger {
                ButtonTrigger::Press => pressed && !was_pressed,
                ButtonTrigger::Release => !pressed && was_pressed,
                _ => false, // TODO: implement other triggers
            };

            if !triggered {
                continue;
            }

            match &binding.action {
                DigitalAction::ShowPanel { panel_id } => {
                    if self.panel_state.active_panel_id.as_ref() == Some(panel_id) {
                        // Toggle off if same panel
                        self.panel_state.active_panel_id = None;
                        events.push(ActionEvent::HidePanel);
                    } else {
                        self.panel_state.active_panel_id = Some(panel_id.clone());
                        self.panel_state.selected_index = 0;
                        self.panel_state.current_page = 0;
                        events.push(ActionEvent::ShowPanel {
                            panel_id: panel_id.clone(),
                        });
                    }
                }
                DigitalAction::HidePanel => {
                    self.panel_state.active_panel_id = None;
                    events.push(ActionEvent::HidePanel);
                }
                DigitalAction::NavigatePanel { direction } => {
                    if self.panel_state.active_panel_id.is_some() {
                        self.navigate_panel(profile, direction);
                        events.push(ActionEvent::NavigatePanel {
                            direction: direction.clone(),
                        });
                    }
                }
                DigitalAction::SelectPanelItem => {
                    if let Some(panel_id) = &self.panel_state.active_panel_id {
                        if let Some(panel) = profile.get_panel(panel_id) {
                            if let Some(preset) = panel.presets.get(self.panel_state.selected_index)
                            {
                                events.push(ActionEvent::ActivatePreset {
                                    preset_id: preset.id.clone(),
                                });
                            }
                        }
                    }
                }
                DigitalAction::ActivatePreset { preset_id } => {
                    events.push(ActionEvent::ActivatePreset {
                        preset_id: preset_id.clone(),
                    });
                }
                DigitalAction::ActivateBoardItem {
                    panel_id, item_id, ..
                } => {
                    events.push(ActionEvent::ActivateBoardItem {
                        panel_id: panel_id.clone(),
                        item_id: item_id.clone(),
                    });
                }
                DigitalAction::ToggleOutput { target_id } => {
                    let current = self.toggle_states.get(target_id).copied().unwrap_or(false);
                    self.toggle_states.insert(target_id.clone(), !current);
                    events.push(ActionEvent::ToggleOutput {
                        target_id: target_id.clone(),
                    });
                }
                DigitalAction::CycleOutput { target_id, values } => {
                    if !values.is_empty() {
                        let idx = self.cycle_indices.get(target_id).copied().unwrap_or(0);
                        let next_idx = (idx + 1) % values.len();
                        self.cycle_indices.insert(target_id.clone(), next_idx);
                        events.push(ActionEvent::CycleOutput {
                            target_id: target_id.clone(),
                            value: values[next_idx].clone(),
                        });
                    }
                }
                DigitalAction::DirectControl { target, value } => {
                    events.push(ActionEvent::Command(MappedCommand::from_target(
                        target,
                        Value::from(*value),
                    )));
                }
                DigitalAction::EStop => {
                    events.push(ActionEvent::EStop);
                }
                DigitalAction::None => {}
            }
        }
    }

    fn navigate_panel(&mut self, profile: &BindingProfile, direction: &NavigateDirection) {
        if let Some(panel_id) = &self.panel_state.active_panel_id {
            if let Some(panel) = profile.get_panel(panel_id) {
                let total_items = panel.presets.len();
                let columns = panel.columns as usize;
                let items_per_page = panel.items_per_page as usize;
                let total_pages = total_items.div_ceil(items_per_page);

                match direction {
                    // Grid navigation
                    NavigateDirection::Up => {
                        if self.panel_state.selected_index >= columns {
                            self.panel_state.selected_index -= columns;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::Down => {
                        if self.panel_state.selected_index + columns < total_items {
                            self.panel_state.selected_index += columns;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::Left => {
                        if self.panel_state.selected_index > 0 {
                            self.panel_state.selected_index -= 1;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::Right => {
                        if self.panel_state.selected_index + 1 < total_items {
                            self.panel_state.selected_index += 1;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    // Linear navigation
                    NavigateDirection::NextItem => {
                        if self.panel_state.selected_index + 1 < total_items {
                            self.panel_state.selected_index += 1;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::PrevItem => {
                        if self.panel_state.selected_index > 0 {
                            self.panel_state.selected_index -= 1;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::NextPage => {
                        if self.panel_state.current_page + 1 < total_pages {
                            self.panel_state.current_page += 1;
                            self.panel_state.selected_index =
                                self.panel_state.current_page * items_per_page;
                        }
                    }
                    NavigateDirection::PrevPage => {
                        if self.panel_state.current_page > 0 {
                            self.panel_state.current_page -= 1;
                            self.panel_state.selected_index =
                                self.panel_state.current_page * items_per_page;
                        }
                    }
                }
            }
        }
    }

    fn get_analog_value(&self, input: &InputState, analog: &AnalogInput) -> f32 {
        match analog {
            AnalogInput::LeftStickX => input.gamepad.left_stick.x,
            AnalogInput::LeftStickY => input.gamepad.left_stick.y,
            AnalogInput::RightStickX => input.gamepad.right_stick.x,
            AnalogInput::RightStickY => input.gamepad.right_stick.y,
            AnalogInput::LeftTrigger => input.gamepad.left_trigger,
            AnalogInput::RightTrigger => input.gamepad.right_trigger,
            // Trackpads report a POSITION that persists after the
            // finger leaves — neither the HID parser nor the evdev
            // reader zeroes it on lift, so `left_pad_x` still holds
            // wherever the thumb last was. Reading that as live input
            // meant lifting off a pad-bound axis left the value pegged
            // at the last deflection: the motor kept running with no
            // hand on the controller, and the mapper's deadstick
            // protections can't help because to them nothing changed —
            // it's a steady non-zero value, re-asserted every tick and
            // every heartbeat.
            //
            // `touched` is the only thing that distinguishes "held at
            // the edge" from "let go at the edge", so a pad axis is
            // input only while it is being touched.
            AnalogInput::LeftPadX => touch_axis(input.left_touchpad.touched, input.left_touchpad.x),
            AnalogInput::LeftPadY => touch_axis(input.left_touchpad.touched, input.left_touchpad.y),
            AnalogInput::RightPadX => touch_axis(input.right_touchpad.touched, input.right_touchpad.x),
            AnalogInput::RightPadY => touch_axis(input.right_touchpad.touched, input.right_touchpad.y),
            // Normalize rate -> -1..1 so the IMU shares the stick's
            // units and InputTransform (deadzone 0.1, clamp -1..1)
            // behaves the same on both. Without this, raw deg/s
            // saturates the clamp on the slightest wrist movement and
            // every gyro binding is effectively a digital switch.
            AnalogInput::GyroPitch => normalize_gyro(input.gyro.pitch),
            AnalogInput::GyroRoll => normalize_gyro(input.gyro.roll),
            AnalogInput::GyroYaw => normalize_gyro(input.gyro.yaw),
        }
    }

    fn get_button_pressed(&self, input: &InputState, button: &DigitalInput) -> bool {
        let button_name = match button {
            DigitalInput::A => "A",
            DigitalInput::B => "B",
            DigitalInput::X => "X",
            DigitalInput::Y => "Y",
            DigitalInput::LB => "LB",
            DigitalInput::RB => "RB",
            DigitalInput::DPadUp => "DPadUp",
            DigitalInput::DPadDown => "DPadDown",
            DigitalInput::DPadLeft => "DPadLeft",
            DigitalInput::DPadRight => "DPadRight",
            DigitalInput::Start => "Start",
            DigitalInput::Select => "Select",
            DigitalInput::LeftStick => "LeftStick",
            DigitalInput::RightStick => "RightStick",
            // Steam Deck back buttons
            DigitalInput::L4 => "L4",
            DigitalInput::R4 => "R4",
            DigitalInput::L5 => "L5",
            DigitalInput::R5 => "R5",
            DigitalInput::Steam => "Steam",
        };
        input.gamepad.buttons.get(button_name).copied().unwrap_or(false)
    }

    fn apply_modifiers(&self, value: f32) -> f32 {
        let mut result = value;

        // Apply precision mode (reduces output based on left trigger)
        if let Some(&precision) = self.modifier_values.get("precision") {
            if precision > 0.0 {
                // At full trigger, reduce to min_scale (e.g., 0.3)
                let min_scale = 0.3;
                let scale = 1.0 - (precision * (1.0 - min_scale));
                result *= scale;
            }
        }

        // Apply speed boost (increases output based on right trigger)
        if let Some(&boost) = self.modifier_values.get("speed_boost") {
            if boost > 0.0 {
                let max_boost = 1.5;
                let scale = 1.0 + (boost * (max_boost - 1.0));
                result *= scale;
            }
        }

        result.clamp(-1.0, 1.0)
    }
}

impl Default for InputMapper {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    //! Behavior lock-down + perf benchmarks for the per-frame input
    //! mapping hot path. Benches are #[ignore]d so they stay out of the
    //! normal `cargo test` run; invoke them with:
    //!   cargo test --release --lib -- --ignored --nocapture bench
    //!
    //! We set the mapper's private fields directly rather than calling
    //! set_profiles()/set_active_profile() — those persist to the real
    //! user data dir (profiles.json) and a test must not clobber the
    //! operator's saved profiles.
    use super::*;
    use crate::bindings::config::*;
    use crate::input::gamepad::GamepadState;
    use crate::input::gyro::{GyroState, TouchpadState};
    use crate::input::manager::InputState;
    use std::time::Instant;

    fn approx(a: f32, b: f32) {
        assert!((a - b).abs() < 1e-5, "expected {b}, got {a}");
    }

    // Identity transform (no deadzone/expo/scale) so binding-level math
    // is exercised without the per-axis transform muddying the numbers —
    // InputTransform::apply has its own dedicated tests in config.rs.
    fn tf0() -> InputTransform {
        InputTransform { deadzone: 0.0, scale: 1.0, expo: 1.0, invert: false }
    }

    fn mapper_with(profile: BindingProfile) -> InputMapper {
        let mut m = InputMapper::new();
        let id = profile.id.clone();
        m.profiles = vec![profile];
        m.active_profile_id = id;
        m.last_analog_values.clear();
        m.last_send_times.clear();
        m.last_button_states.clear();
        m.modifier_values.clear();
        m.toggle_states.clear();
        m.cycle_indices.clear();
        m.panel_state = PanelState::default();
        m
    }

    fn analog_profile(binding: AnalogBinding) -> BindingProfile {
        let mut p = BindingProfile::new("test", "Test");
        p.analog_bindings = vec![binding];
        p
    }

    fn digital_profile(binding: DigitalBinding) -> BindingProfile {
        let mut p = BindingProfile::new("test", "Test");
        p.digital_bindings = vec![binding];
        p
    }

    fn input_right_stick(x: f32, y: f32) -> InputState {
        let mut gp = GamepadState { connected: true, ..Default::default() };
        gp.right_stick.x = x;
        gp.right_stick.y = y;
        InputState {
            gamepad: gp,
            gyro: GyroState::default(),
            left_touchpad: TouchpadState::default(),
            right_touchpad: TouchpadState::default(),
        }
    }

    fn input_buttons(pairs: &[(&str, bool)]) -> InputState {
        let mut gp = GamepadState { connected: true, ..Default::default() };
        for (name, pressed) in pairs {
            gp.buttons.insert((*name).to_string(), *pressed);
        }
        InputState {
            gamepad: gp,
            gyro: GyroState::default(),
            left_touchpad: TouchpadState::default(),
            right_touchpad: TouchpadState::default(),
        }
    }

    // Value written to a specific Topic channel, if any command targets it.
    fn topic_cmd(events: &[ActionEvent], channel: &str) -> Option<f64> {
        for e in events {
            if let ActionEvent::Command(MappedCommand::Topic { channel: c, value, .. }) = e {
                if c == channel {
                    return value.as_f64();
                }
            }
        }
        None
    }

    fn has_estop(events: &[ActionEvent]) -> bool {
        events.iter().any(|e| matches!(e, ActionEvent::EStop))
    }

    fn cycle_value(events: &[ActionEvent]) -> Option<String> {
        events.iter().find_map(|e| match e {
            ActionEvent::CycleOutput { value, .. } => Some(value.clone()),
            _ => None,
        })
    }

    fn fresh_mapper() -> InputMapper {
        let mut m = InputMapper::new();
        m.profiles = vec![crate::bindings::presets::create_default_profile()];
        m.active_profile_id = "default".to_string();
        // Clear change-detection caches so each test starts deterministic.
        m.last_analog_values.clear();
        m.last_send_times.clear();
        m.last_button_states.clear();
        m
    }

    fn input_left_stick(x: f32, y: f32) -> InputState {
        let mut gp = GamepadState { connected: true, ..Default::default() };
        gp.left_stick.x = x;
        gp.left_stick.y = y;
        InputState {
            gamepad: gp,
            gyro: GyroState::default(),
            left_touchpad: TouchpadState::default(),
            right_touchpad: TouchpadState::default(),
        }
    }

    fn cmd_value(cmd: &MappedCommand) -> f64 {
        match cmd {
            MappedCommand::Topic { value, .. } | MappedCommand::WsInput { value, .. } => {
                value.as_f64().unwrap_or(f64::NAN)
            }
        }
    }

    /// Values of the Command events in emission order, non-Command
    /// events dropped. Lets a test read as "this tick sent [0.0, 0.0]".
    ///
    /// Rounded to 1e-4: the pipeline is f32 and widening to f64 leaves
    /// artifacts (0.8f32 -> 0.800000011920929) that would make every
    /// literal comparison unreadable. Well below the mapper's own
    /// 0.001 change threshold, so it can't mask a real difference.
    fn cmd_values(events: &[ActionEvent]) -> Vec<f64> {
        events
            .iter()
            .filter_map(|e| match e {
                ActionEvent::Command(cmd) => Some((cmd_value(cmd) * 10_000.0).round() / 10_000.0),
                _ => None,
            })
            .collect()
    }

    // ── behavior (the "don't break anything" net) ───────────────────

    #[test]
    fn deflected_stick_emits_commands() {
        let mut m = fresh_mapper();
        let events = m.process(&input_left_stick(0.0, 0.9));
        let cmds = events.iter().filter(|e| matches!(e, ActionEvent::Command(_))).count();
        assert!(cmds > 0, "deflected stick must emit Command(s); got {:?}", events);
    }

    #[test]
    fn deflection_values_finite_and_nonzero() {
        let mut m = fresh_mapper();
        let events = m.process(&input_left_stick(0.0, 0.9));
        let mut saw_nonzero = false;
        for e in &events {
            if let ActionEvent::Command(cmd) = e {
                let v = cmd_value(cmd);
                assert!(v.is_finite(), "command value must be finite");
                if v.abs() > 1e-6 {
                    saw_nonzero = true;
                }
            }
        }
        assert!(saw_nonzero, "strong deflection should produce a non-zero command");
    }

    #[test]
    fn process_is_deterministic() {
        // Two independent mappers, same input → identical event stream.
        // This is the core invariant the profile-access refactor must
        // preserve (it changes HOW the active profile is read, not the math).
        let mut a = fresh_mapper();
        let mut b = fresh_mapper();
        let inp = input_left_stick(0.3, 0.7);
        let ea = a.process(&inp);
        let eb = b.process(&inp);
        assert_eq!(ea.len(), eb.len(), "event counts must match");
        assert_eq!(
            serde_json::to_string(&ea).unwrap(),
            serde_json::to_string(&eb).unwrap(),
            "event streams must be byte-identical",
        );
    }

    #[test]
    fn deadstick_after_deflection_emits_zero() {
        let mut m = fresh_mapper();
        let _ = m.process(&input_left_stick(0.0, 0.9)); // deflect
        let stop = m.process(&input_left_stick(0.0, 0.0)); // release
        let mut saw_zero = false;
        for e in &stop {
            if let ActionEvent::Command(cmd) = e {
                if cmd_value(cmd).abs() <= 1e-6 {
                    saw_zero = true;
                }
            }
        }
        assert!(saw_zero, "release must emit a zero stop command; got {:?}", stop);
    }

    // ── emission cadence (2026-07 latency audit lock-down) ──────────────

    #[test]
    fn held_deflection_emits_once_then_goes_quiet() {
        // REPLACES held_deflection_reemits_every_tick.
        //
        // That test pinned the old value_active branch, which re-emitted
        // every non-zero value on every 4 ms tick. Its stated reason was
        // to plug the client throttle's trailing-edge drop — a write
        // inside the THROTTLE_MS window was discarded while the mapper
        // recorded it as sent, so without a blanket re-emit a mid-stroke
        // setpoint waited for the 500 ms heartbeat. It told the next
        // reader to "revisit the throttle before shipping that", which is
        // what happened: the throttle now returns THROTTLED and the input
        // loop retries via note_send_failed, so the drop is covered
        // precisely instead of by brute force.
        //
        // What that re-emit was NOT doing is keeping anything downstream
        // alive — see the should_send comment for the server/firmware
        // cadence contract, which is built on the heartbeat.
        //
        // Count non-zero emissions only: the first process() also emits a
        // one-time zero baseline for every idle binding (heartbeat_due is
        // true for a key that has never sent), which then goes quiet.
        fn nonzero_cmds(events: &[ActionEvent]) -> usize {
            events.iter()
                .filter(|e| match e {
                    ActionEvent::Command(cmd) => cmd_value(cmd).abs() > 0.001,
                    _ => false,
                })
                .count()
        }
        let mut m = fresh_mapper();
        let inp = input_left_stick(0.0, 0.9);
        assert!(nonzero_cmds(&m.process(&inp)) > 0, "deflection must emit");
        assert_eq!(
            nonzero_cmds(&m.process(&inp)),
            0,
            "an unchanged held deflection must not re-emit; the wire value \
             already stands and the heartbeat re-asserts it",
        );
    }

    /// The trailing-edge case the old blanket re-emit existed for: a
    /// mid-stroke value the client refused (inside its throttle window)
    /// must come back on the next tick, not wait for the heartbeat.
    #[test]
    fn refused_midstroke_value_is_reemitted() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));

        let held = input_right_stick(0.0, 0.45);
        assert_eq!(cmd_values(&m.process(&held)), vec![0.45]);
        assert!(
            m.process(&held).is_empty(),
            "baseline: a delivered value stays quiet",
        );

        // The client throttled it — value never reached the server.
        m.note_send_failed(&MappedCommand::Topic {
            topic: "/tracks".into(),
            channel: "left".into(),
            value: Value::from(0.45),
        });
        assert_eq!(
            cmd_values(&m.process(&held)),
            vec![0.45],
            "a throttled mid-stroke value must be retried next tick",
        );
    }

    #[test]
    fn idle_zero_is_quiet_within_heartbeat_window() {
        // A resting stick must NOT stream zeros between heartbeats —
        // that's the no-signal-overkill half of the contract.
        let mut m = fresh_mapper();
        let _ = m.process(&input_left_stick(0.0, 0.9));
        let _ = m.process(&input_left_stick(0.0, 0.0)); // release → stop sent
        let idle = m.process(&input_left_stick(0.0, 0.0));
        let cmds = idle.iter()
            .filter(|e| matches!(e, ActionEvent::Command(_))).count();
        assert_eq!(cmds, 0, "resting stick must be quiet inside the heartbeat window");
    }

    // ── release on background (safety) ───────────────────────────────
    //
    // Pausing the input loop when the window loses focus is only safe if
    // something stops the motors first. Without these, a deflected stick
    // at blur leaves the last command standing and the firmware dead-man
    // (1250 ms) is the only thing that eventually stops it.

    #[test]
    fn release_all_analog_zeroes_a_deflected_axis() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));

        assert_eq!(cmd_values(&m.process(&input_right_stick(0.0, 0.9))), vec![0.9]);
        assert_eq!(
            cmd_values(&m.release_all_analog()),
            vec![0.0],
            "backgrounding must command zero, not just stop talking",
        );
    }

    /// Both tracks, or the un-zeroed one keeps driving and the robot
    /// pirouettes off while the operator is in the Steam overlay.
    #[test]
    fn release_all_analog_zeroes_both_differential_channels() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DifferentialDrive {
                topic: "/tracks".into(),
                left_channel: "left".into(),
                right_channel: "right".into(),
                throttle_transform: tf0(),
                turn_transform: tf0(),
            },
            enabled: true,
        }));

        m.process(&input_right_stick(0.0, 0.8));
        assert_eq!(cmd_values(&m.release_all_analog()), vec![0.0, 0.0]);
    }

    /// Releasing must re-arm, so returning to a still-held stick resumes
    /// motion rather than sitting dead until the next heartbeat.
    #[test]
    fn release_all_analog_rearms_for_refocus() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));

        let held = input_right_stick(0.0, 0.7);
        m.process(&held);
        m.release_all_analog();
        assert_eq!(
            cmd_values(&m.process(&held)),
            vec![0.7],
            "refocus must re-assert the live stick position",
        );
    }

    /// Analog-only by design: running the full process() path against a
    /// neutral InputState would also present every button as released and
    /// fire Release-triggered bindings — a phantom action caused by the
    /// operator opening an overlay.
    #[test]
    fn release_all_analog_does_not_fire_digital_bindings() {
        let mut profile = BindingProfile::new("test", "Test");
        profile.analog_bindings = vec![AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }];
        profile.digital_bindings = vec![DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Release,
            action: DigitalAction::ShowPanel { panel_id: "p".into() },
            enabled: true,
        }];
        let mut m = mapper_with(profile);

        m.process(&input_buttons(&[("A", true)]));
        let events = m.release_all_analog();
        assert!(
            !events.iter().any(|e| matches!(e, ActionEvent::ShowPanel { .. })),
            "a release must not trigger digital actions: {events:?}",
        );
    }

    #[test]
    fn release_all_analog_skips_disabled_bindings() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: false,
        }));
        assert!(m.release_all_analog().is_empty());
    }

    // ── link-up re-assertion ─────────────────────────────────────────
    //
    // While disconnected the input loop drops commands without sending
    // (no link, and the send path would churn locks for nothing), but
    // the mapper still records them as sent. forget_all_sends() is what
    // makes that safe: on link-up every bound axis is re-asserted, so a
    // fresh server is told the true current value instead of inheriting
    // the mapper's memory of a conversation that never happened.

    #[test]
    fn forget_all_sends_reasserts_a_held_deflection() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));

        let held = input_right_stick(0.0, 0.6);
        assert_eq!(cmd_values(&m.process(&held)), vec![0.6]);

        m.forget_all_sends();
        assert_eq!(
            cmd_values(&m.process(&held)),
            vec![0.6],
            "link-up must re-assert a still-held deflection",
        );
    }

    /// The zero case is the one that matters: a stick released while the
    /// link was down must be re-asserted as zero on link-up, or the
    /// server comes back up knowing nothing about that axis.
    #[test]
    fn forget_all_sends_reasserts_a_resting_axis() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));

        m.process(&input_right_stick(0.0, 0.6));
        m.process(&input_right_stick(0.0, 0.0));
        let resting = input_right_stick(0.0, 0.0);
        assert!(
            m.process(&resting).is_empty(),
            "baseline: a resting axis is quiet inside the heartbeat window",
        );

        m.forget_all_sends();
        assert_eq!(
            cmd_values(&m.process(&resting)),
            vec![0.0],
            "link-up must re-assert zero, not stay quiet",
        );
    }

    // ── trackpad release (a lifted finger is not input) ───────────────

    fn input_left_pad(x: f32, y: f32, touched: bool) -> InputState {
        InputState {
            gamepad: GamepadState { connected: true, ..Default::default() },
            gyro: GyroState::default(),
            left_touchpad: TouchpadState { x, y, touched, clicked: false },
            right_touchpad: TouchpadState::default(),
        }
    }

    fn pad_profile(input: AnalogInput) -> BindingProfile {
        analog_profile(AnalogBinding {
            input,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        })
    }

    /// Trackpads report a position that PERSISTS after the finger
    /// leaves — nothing zeroes it on lift. Reading it raw meant letting
    /// go of a pad-bound axis left the motor at the last deflection, and
    /// the deadstick machinery can't catch it: to the mapper the value
    /// simply never changed.
    #[test]
    fn lifting_off_a_trackpad_commands_zero() {
        let mut m = mapper_with(pad_profile(AnalogInput::LeftPadX));

        assert_eq!(
            cmd_values(&m.process(&input_left_pad(0.8, 0.0, true))),
            vec![0.8],
            "a touched pad drives the axis",
        );

        // Finger lifted at the edge: position still reads 0.8.
        assert_eq!(
            cmd_values(&m.process(&input_left_pad(0.8, 0.0, false))),
            vec![0.0],
            "releasing the pad must command zero, not hold the last position",
        );
    }

    #[test]
    fn untouched_trackpad_never_starts_motion() {
        let mut m = mapper_with(pad_profile(AnalogInput::LeftPadY));
        // A stale position from a previous session/subscriber must not
        // read as input just because it is non-zero.
        let events = m.process(&input_left_pad(0.0, -0.9, false));
        assert_eq!(
            cmd_values(&events),
            vec![0.0],
            "an untouched pad is neutral regardless of its position",
        );
    }

    /// The release has to survive the same refusal path as a stick's —
    /// this is the trackpad equivalent of refused_stop_is_reemitted.
    #[test]
    fn refused_trackpad_release_is_reemitted() {
        let mut m = mapper_with(pad_profile(AnalogInput::LeftPadX));
        m.process(&input_left_pad(0.8, 0.0, true));
        assert_eq!(cmd_values(&m.process(&input_left_pad(0.8, 0.0, false))), vec![0.0]);
        assert!(
            m.process(&input_left_pad(0.8, 0.0, false)).is_empty(),
            "baseline: a delivered release stays quiet",
        );

        m.note_send_failed(&MappedCommand::Topic {
            topic: "/tracks".into(),
            channel: "left".into(),
            value: Value::from(0.0),
        });
        assert_eq!(
            cmd_values(&m.process(&input_left_pad(0.8, 0.0, false))),
            vec![0.0],
            "a refused pad release must be retried on the next tick",
        );
    }

    // ── IMU bindings + demand signal ─────────────────────────────────

    fn input_gyro(pitch: f32, roll: f32, yaw: f32) -> InputState {
        InputState {
            gamepad: GamepadState { connected: true, ..Default::default() },
            gyro: GyroState { pitch, roll, yaw },
            left_touchpad: TouchpadState::default(),
            right_touchpad: TouchpadState::default(),
        }
    }

    fn gyro_binding(input: AnalogInput, enabled: bool) -> AnalogBinding {
        AnalogBinding {
            input,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/head".into(),
                    channel: "pan".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled,
        }
    }

    /// Raw gyro is deg/s at +/-2000 full scale; every other analog
    /// input is -1..1. Without normalization the shared InputTransform
    /// clamp turns any real wrist movement into a hard +/-1, making a
    /// gyro binding behave like a switch instead of a proportional axis.
    #[test]
    fn gyro_rates_are_normalized_to_the_stick_range() {
        let mut m = mapper_with(analog_profile(gyro_binding(AnalogInput::GyroPitch, true)));
        // Half of full scale -> half deflection.
        assert_eq!(cmd_values(&m.process(&input_gyro(1000.0, 0.0, 0.0))), vec![0.5]);
        // Beyond full scale saturates rather than exceeding the range.
        assert_eq!(cmd_values(&m.process(&input_gyro(5000.0, 0.0, 0.0))), vec![1.0]);
        assert_eq!(cmd_values(&m.process(&input_gyro(-5000.0, 0.0, 0.0))), vec![-1.0]);
    }

    #[test]
    fn each_gyro_axis_reads_its_own_channel() {
        for (input, sample, expect) in [
            (AnalogInput::GyroPitch, input_gyro(2000.0, 0.0, 0.0), 1.0),
            (AnalogInput::GyroRoll, input_gyro(0.0, 2000.0, 0.0), 1.0),
            (AnalogInput::GyroYaw, input_gyro(0.0, 0.0, 2000.0), 1.0),
        ] {
            let mut m = mapper_with(analog_profile(gyro_binding(input.clone(), true)));
            assert_eq!(
                cmd_values(&m.process(&sample)),
                vec![expect],
                "{input:?} must read its own axis",
            );
        }
    }

    // uses_gyro is the switch that decides whether the sensor is
    // powered at all, so both directions matter: a false negative
    // leaves a configured binding dead, a false positive burns battery
    // for the whole session.

    #[test]
    fn uses_gyro_is_false_without_a_gyro_binding() {
        let m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));
        assert!(!m.uses_gyro(), "stick-only profile must leave the IMU off");
    }

    #[test]
    fn uses_gyro_is_true_with_an_enabled_gyro_binding() {
        let m = mapper_with(analog_profile(gyro_binding(AnalogInput::GyroYaw, true)));
        assert!(m.uses_gyro());
    }

    #[test]
    fn uses_gyro_ignores_disabled_bindings() {
        let m = mapper_with(analog_profile(gyro_binding(AnalogInput::GyroYaw, false)));
        assert!(
            !m.uses_gyro(),
            "a disabled binding must not keep the sensor powered",
        );
    }

    /// Demand follows the ACTIVE profile. Switching to a profile that
    /// doesn't use the IMU has to release it, or the sensor stays on
    /// for the rest of the session after one gyro profile is touched.
    #[test]
    fn uses_gyro_tracks_the_active_profile() {
        let mut gyro_p = BindingProfile::new("gyro", "Gyro");
        gyro_p.analog_bindings = vec![gyro_binding(AnalogInput::GyroPitch, true)];
        let plain = BindingProfile::new("plain", "Plain");

        let mut m = InputMapper::new();
        m.profiles = vec![gyro_p, plain];
        m.active_profile_id = "gyro".to_string();
        assert!(m.uses_gyro());

        m.set_active_profile("plain");
        assert!(!m.uses_gyro(), "switching away must release the IMU");

        m.set_active_profile("gyro");
        assert!(m.uses_gyro(), "switching back must re-acquire it");
    }

    // ── refused-send recovery (deadstick must never be lost) ──────────
    //
    // The analog paths commit last_analog_values/last_send_times when a
    // command is QUEUED, not when it lands. If the WS client then
    // refuses it, the mapper has already gone quiet about that channel.
    // For a return-to-zero that means a motor keeps running. These pin
    // note_send_failed as the undo.

    /// Deflect, then release, then have the release refused. The mapper
    /// must re-emit the zero on the very next tick — not sit on it for
    /// HEARTBEAT_MS with the motor still turning.
    #[test]
    fn refused_stop_is_reemitted_on_the_next_tick() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));

        // Stick deflected.
        let deflect = m.process(&input_right_stick(0.0, 0.8));
        assert_eq!(cmd_values(&deflect), vec![0.8], "deflection must be sent");

        // Stick released — the mapper emits the stop and records it sent.
        let release = m.process(&input_right_stick(0.0, 0.0));
        assert_eq!(cmd_values(&release), vec![0.0], "release must emit a stop");

        // Without the undo the mapper now believes the zero landed, and
        // an immediate re-tick produces nothing.
        let quiet = m.process(&input_right_stick(0.0, 0.0));
        assert!(cmd_values(&quiet).is_empty(), "baseline: a delivered stop stays quiet");

        // Now say that stop was refused.
        m.note_send_failed(&MappedCommand::Topic {
            topic: "/tracks".into(),
            channel: "left".into(),
            value: Value::from(0.0),
        });

        let retry = m.process(&input_right_stick(0.0, 0.0));
        assert_eq!(
            cmd_values(&retry),
            vec![0.0],
            "a refused stop must be retried on the next tick, not the heartbeat",
        );
    }

    /// Differential drive heartbeats the left/right pair off one timer,
    /// so a refusal on either channel has to re-arm both — clearing only
    /// the failed channel can leave the pair's timer intact and the
    /// opposite track running.
    #[test]
    fn refused_stop_rearms_both_differential_drive_channels() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DifferentialDrive {
                topic: "/tracks".into(),
                left_channel: "left".into(),
                right_channel: "right".into(),
                throttle_transform: tf0(),
                turn_transform: tf0(),
            },
            enabled: true,
        }));

        m.process(&input_right_stick(0.0, 0.8));
        let release = m.process(&input_right_stick(0.0, 0.0));
        assert_eq!(cmd_values(&release), vec![0.0, 0.0], "both tracks must stop");
        assert!(m.process(&input_right_stick(0.0, 0.0)).is_empty(), "baseline quiet");

        // Only the RIGHT channel's send failed...
        m.note_send_failed(&MappedCommand::Topic {
            topic: "/tracks".into(),
            channel: "right".into(),
            value: Value::from(0.0),
        });

        // ...but both must be re-asserted, because they share a timer.
        assert_eq!(
            cmd_values(&m.process(&input_right_stick(0.0, 0.0))),
            vec![0.0, 0.0],
            "a refusal on one track must re-arm the pair",
        );
    }

    /// note_send_failed must not blow away unrelated channels' state —
    /// over-clearing costs a redundant send, but clearing a different
    /// robot's target on every transient would be a traffic amplifier.
    #[test]
    fn refused_send_does_not_rearm_unrelated_targets() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickY,
            action: AnalogAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/tracks".into(),
                    channel: "left".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));

        m.process(&input_right_stick(0.0, 0.8));
        m.process(&input_right_stick(0.0, 0.0));
        assert!(m.process(&input_right_stick(0.0, 0.0)).is_empty(), "baseline quiet");

        // A failure on a completely different topic must leave this
        // channel's bookkeeping alone.
        m.note_send_failed(&MappedCommand::Topic {
            topic: "/arm".into(),
            channel: "shoulder".into(),
            value: Value::from(0.0),
        });
        assert!(
            m.process(&input_right_stick(0.0, 0.0)).is_empty(),
            "an unrelated failure must not re-arm this target",
        );
    }

    #[test]
    fn heartbeat_reasserts_idle_value_after_interval() {
        // A dropped stop packet must be re-covered by the heartbeat:
        // backdate the send stamps past HEARTBEAT_MS and the idle zero
        // must be re-emitted.
        let mut m = fresh_mapper();
        let _ = m.process(&input_left_stick(0.0, 0.9));
        let _ = m.process(&input_left_stick(0.0, 0.0));
        let quiet = m.process(&input_left_stick(0.0, 0.0));
        assert_eq!(
            quiet.iter().filter(|e| matches!(e, ActionEvent::Command(_))).count(),
            0,
        );
        let past = Instant::now() - std::time::Duration::from_millis(HEARTBEAT_MS + 50);
        for t in m.last_send_times.values_mut() {
            *t = past;
        }
        let hb = m.process(&input_left_stick(0.0, 0.0));
        assert!(
            hb.iter().filter(|e| matches!(e, ActionEvent::Command(_))).count() > 0,
            "heartbeat must re-assert the idle value after HEARTBEAT_MS",
        );
    }

    #[test]
    fn no_profile_emits_nothing() {
        let mut m = fresh_mapper();
        m.profiles.clear();
        m.active_profile_id = "nope".to_string();
        assert!(m.process(&input_left_stick(0.0, 0.9)).is_empty());
    }

    // ── differential drive (tank mixing) ────────────────────────────

    fn diff_drive_profile() -> BindingProfile {
        analog_profile(AnalogBinding {
            input: AnalogInput::LeftStickY,
            action: AnalogAction::DifferentialDrive {
                topic: "/tracks".into(),
                left_channel: "left".into(),
                right_channel: "right".into(),
                throttle_transform: tf0(),
                turn_transform: tf0(),
            },
            enabled: true,
        })
    }

    #[test]
    fn diff_drive_mixes_throttle_and_turn() {
        // throttle (y) = 0.5, turn (x) = 0.5 → left = 1.0, right = 0.0.
        let mut m = mapper_with(diff_drive_profile());
        let ev = m.process(&input_left_stick(0.5, 0.5));
        approx(topic_cmd(&ev, "left").unwrap() as f32, 1.0);
        approx(topic_cmd(&ev, "right").unwrap() as f32, 0.0);
    }

    #[test]
    fn diff_drive_pure_throttle_drives_both_equally() {
        // throttle 0.8, no turn → both tracks 0.8.
        let mut m = mapper_with(diff_drive_profile());
        let ev = m.process(&input_left_stick(0.0, 0.8));
        approx(topic_cmd(&ev, "left").unwrap() as f32, 0.8);
        approx(topic_cmd(&ev, "right").unwrap() as f32, 0.8);
    }

    #[test]
    fn diff_drive_normalizes_when_sum_exceeds_one() {
        // throttle 1.0 + turn 1.0 → left 2.0, right 0.0; proportional
        // normalize divides by max (2.0) → left 1.0, right 0.0. Without
        // this the left track would saturate while right does nothing,
        // pulling the robot off the commanded arc.
        let mut m = mapper_with(diff_drive_profile());
        let ev = m.process(&input_left_stick(1.0, 1.0));
        approx(topic_cmd(&ev, "left").unwrap() as f32, 1.0);
        approx(topic_cmd(&ev, "right").unwrap() as f32, 0.0);
    }

    // ── modifiers (precision / speed boost) ──────────────────────────

    #[test]
    fn precision_modifier_scales_down() {
        let mut m = fresh_mapper();
        m.modifier_values.insert("precision".into(), 1.0); // full trigger
        approx(m.apply_modifiers(1.0), 0.3); // 1 - 1*(1-0.3) = 0.3
        m.modifier_values.insert("precision".into(), 0.5);
        approx(m.apply_modifiers(1.0), 0.65); // 1 - 0.5*0.7
    }

    #[test]
    fn speed_boost_modifier_scales_up_and_clamps() {
        let mut m = fresh_mapper();
        m.modifier_values.insert("speed_boost".into(), 1.0); // full trigger
        approx(m.apply_modifiers(0.5), 0.75); // 0.5 * 1.5
        approx(m.apply_modifiers(1.0), 1.0); // 1.5 → clamp 1.0
    }

    #[test]
    fn modifiers_compose_then_clamp() {
        let mut m = fresh_mapper();
        m.modifier_values.insert("precision".into(), 1.0);   // ×0.3
        m.modifier_values.insert("speed_boost".into(), 1.0); // ×1.5
        approx(m.apply_modifiers(1.0), 0.45); // 1 * 0.3 * 1.5
    }

    #[test]
    fn no_modifiers_is_identity() {
        let m = fresh_mapper();
        approx(m.apply_modifiers(0.7), 0.7);
        approx(m.apply_modifiers(-0.7), -0.7);
    }

    // ── digital actions ──────────────────────────────────────────────

    #[test]
    fn estop_button_emits_estop() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::Select,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::EStop,
            enabled: true,
        }));
        let ev = m.process(&input_buttons(&[("Select", true)]));
        assert!(has_estop(&ev), "Select press must emit EStop; got {ev:?}");
    }

    #[test]
    fn press_triggers_on_rising_edge_only() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::EStop,
            enabled: true,
        }));
        // Rising edge fires once.
        assert!(has_estop(&m.process(&input_buttons(&[("A", true)]))));
        // Held (still pressed, no new edge) does not re-fire.
        assert!(!has_estop(&m.process(&input_buttons(&[("A", true)]))));
        // Release does not fire a Press binding.
        assert!(!has_estop(&m.process(&input_buttons(&[("A", false)]))));
    }

    #[test]
    fn release_trigger_fires_on_falling_edge() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Release,
            action: DigitalAction::EStop,
            enabled: true,
        }));
        assert!(!has_estop(&m.process(&input_buttons(&[("A", true)])))); // press: no
        assert!(has_estop(&m.process(&input_buttons(&[("A", false)])))); // release: yes
    }

    #[test]
    fn hold_doubletap_longpress_are_not_yet_implemented() {
        // Lock the current TODO behaviour: these triggers never fire.
        // When implemented, this test breaks and prompts an update —
        // better than silently shipping a no-op binding.
        for trig in [ButtonTrigger::Hold, ButtonTrigger::DoubleTap, ButtonTrigger::LongPress] {
            let mut m = mapper_with(digital_profile(DigitalBinding {
                input: DigitalInput::A,
                trigger: trig,
                action: DigitalAction::EStop,
                enabled: true,
            }));
            assert!(!has_estop(&m.process(&input_buttons(&[("A", true)]))));
            assert!(!has_estop(&m.process(&input_buttons(&[("A", true)]))));
        }
    }

    #[test]
    fn disabled_binding_does_nothing() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::Select,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::EStop,
            enabled: false,
        }));
        assert!(!has_estop(&m.process(&input_buttons(&[("Select", true)]))));
    }

    #[test]
    fn toggle_output_flips_each_press() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::ToggleOutput { target_id: "motor".into() },
            enabled: true,
        }));
        m.process(&input_buttons(&[("A", true)]));   // press → true
        assert_eq!(m.toggle_states.get("motor"), Some(&true));
        m.process(&input_buttons(&[("A", false)]));  // release (no edge)
        m.process(&input_buttons(&[("A", true)]));   // press → false
        assert_eq!(m.toggle_states.get("motor"), Some(&false));
    }

    #[test]
    fn cycle_output_advances_and_wraps() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::CycleOutput {
                target_id: "mode".into(),
                values: vec!["a".into(), "b".into(), "c".into()],
            },
            enabled: true,
        }));
        let press = |m: &mut InputMapper| {
            let e = m.process(&input_buttons(&[("A", true)]));
            m.process(&input_buttons(&[("A", false)]));
            cycle_value(&e)
        };
        assert_eq!(press(&mut m).as_deref(), Some("b"));
        assert_eq!(press(&mut m).as_deref(), Some("c"));
        assert_eq!(press(&mut m).as_deref(), Some("a")); // wrap
    }

    #[test]
    fn show_panel_toggles_open_then_closed() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::Y,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::ShowPanel { panel_id: "poses".into() },
            enabled: true,
        }));
        let open = m.process(&input_buttons(&[("Y", true)]));
        assert!(open.iter().any(|e| matches!(e, ActionEvent::ShowPanel { panel_id } if panel_id == "poses")));
        assert_eq!(m.panel_state.active_panel_id.as_deref(), Some("poses"));

        m.process(&input_buttons(&[("Y", false)])); // release
        let close = m.process(&input_buttons(&[("Y", true)])); // same button again
        assert!(close.iter().any(|e| matches!(e, ActionEvent::HidePanel)));
        assert_eq!(m.panel_state.active_panel_id, None);
    }

    #[test]
    fn digital_direct_control_sends_fixed_value() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::B,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/saint/horn".into(),
                    channel: "on".into(),
                    name: None,
                },
                value: 1.0,
            },
            enabled: true,
        }));
        let ev = m.process(&input_buttons(&[("B", true)]));
        approx(topic_cmd(&ev, "on").unwrap() as f32, 1.0);
    }

    // ── target routing ───────────────────────────────────────────────

    #[test]
    fn direct_control_routes_to_ws_input_target() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickX,
            action: AnalogAction::DirectControl {
                target: ControlTarget::WsInput {
                    sheet_id: "sheetA".into(),
                    input_id: "in1".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));
        let ev = m.process(&input_right_stick(0.8, 0.0));
        let routed = ev.iter().find_map(|e| match e {
            ActionEvent::Command(MappedCommand::WsInput { sheet_id, input_id, value }) =>
                Some((sheet_id.clone(), input_id.clone(), value.as_f64().unwrap_or(f64::NAN))),
            _ => None,
        });
        let (sheet, input, value) = routed.expect("expected a WsInput command");
        assert_eq!(sheet, "sheetA");
        assert_eq!(input, "in1");
        approx(value as f32, 0.8);
    }

    // ── panel grid navigation ────────────────────────────────────────

    fn panel_profile(presets: usize, columns: u32, items_per_page: u32) -> BindingProfile {
        let mut p = BindingProfile::new("test", "Test");
        let presets = (0..presets)
            .map(|i| Preset {
                id: format!("p{i}"),
                name: format!("P{i}"),
                icon: None,
                color: None,
                preset_type: PresetType::Sound,
                data: PresetData::Sound(SoundPresetData {
                    sound_id: "s".into(),
                    volume: 1.0,
                    priority: 1,
                }),
            })
            .collect();
        p.preset_panels = vec![PresetPanel {
            id: "grid".into(),
            name: "Grid".into(),
            icon: "i".into(),
            color: "#fff".into(),
            presets,
            layout: PanelLayout::Grid,
            columns,
            items_per_page,
            source: None,
        }];
        p
    }

    #[test]
    fn navigate_grid_moves_within_bounds() {
        // 6 items, 4 columns, single page.
        let profile = panel_profile(6, 4, 8);
        let mut m = mapper_with(profile.clone());
        m.panel_state.active_panel_id = Some("grid".into());

        m.navigate_panel(&profile, &NavigateDirection::Right);
        assert_eq!(m.panel_state.selected_index, 1);

        m.panel_state.selected_index = 0;
        m.navigate_panel(&profile, &NavigateDirection::Down); // +columns
        assert_eq!(m.panel_state.selected_index, 4);

        m.navigate_panel(&profile, &NavigateDirection::Up); // back to row 0
        assert_eq!(m.panel_state.selected_index, 0);
    }

    #[test]
    fn navigate_grid_clamps_at_edges() {
        let profile = panel_profile(6, 4, 8);
        let mut m = mapper_with(profile.clone());
        m.panel_state.active_panel_id = Some("grid".into());

        // Up from row 0 is a no-op.
        m.navigate_panel(&profile, &NavigateDirection::Up);
        assert_eq!(m.panel_state.selected_index, 0);
        // Left from index 0 is a no-op.
        m.navigate_panel(&profile, &NavigateDirection::Left);
        assert_eq!(m.panel_state.selected_index, 0);
        // Right past the last item (index 5) is a no-op.
        m.panel_state.selected_index = 5;
        m.navigate_panel(&profile, &NavigateDirection::Right);
        assert_eq!(m.panel_state.selected_index, 5);
        // Down would land on index 9 (>= 6) → no-op.
        m.panel_state.selected_index = 5;
        m.navigate_panel(&profile, &NavigateDirection::Down);
        assert_eq!(m.panel_state.selected_index, 5);
    }

    #[test]
    fn navigate_grid_pages() {
        // 10 items, 4 columns, 8 per page → 2 pages.
        let profile = panel_profile(10, 4, 8);
        let mut m = mapper_with(profile.clone());
        m.panel_state.active_panel_id = Some("grid".into());

        m.navigate_panel(&profile, &NavigateDirection::NextPage);
        assert_eq!(m.panel_state.current_page, 1);
        assert_eq!(m.panel_state.selected_index, 8); // first item of page 2

        m.navigate_panel(&profile, &NavigateDirection::NextPage); // already last page
        assert_eq!(m.panel_state.current_page, 1);

        m.navigate_panel(&profile, &NavigateDirection::PrevPage);
        assert_eq!(m.panel_state.current_page, 0);
        assert_eq!(m.panel_state.selected_index, 0);
    }

    // ── benchmarks (#[ignore]; run with --ignored --nocapture) ───────

    #[test]
    #[ignore = "benchmark — run explicitly with --ignored --nocapture"]
    fn bench_process_per_frame() {
        let mut m = fresh_mapper();
        let inp = input_left_stick(0.4, 0.7); // actively deflected → emits every frame
        let n: u32 = 2_000_000;
        for _ in 0..10_000 {
            let _ = m.process(&inp);
        }
        let mut sink = 0usize;
        let t0 = Instant::now();
        for _ in 0..n {
            sink += m.process(&inp).len();
        }
        let el = t0.elapsed();
        println!(
            "\n[bench] InputMapper::process() per frame: {:.1} ns/call  ({:.0} calls/s, n={}, sink={})",
            el.as_nanos() as f64 / n as f64,
            n as f64 / el.as_secs_f64(),
            n,
            sink,
        );
    }
}
