"""
PlatformIO pre-build script: generate include/version.h

Runs at the start of each build to embed version info, git hash,
and build timestamps into the firmware binary.
"""

import subprocess
import time
import os

Import("env")

print(f"Running version header generation script")
#print(f"Current Build flags", env.get("BUILD_FLAGS", []))
#print(f"Current CPPDEFINES", env.get("CPPDEFINES", []))

# Extract version from build flags
version_major = "0"
version_minor = "0"
version_patch = "0"

for flag in env.get("BUILD_FLAGS", []):
    flag_str = str(flag)
    if "FIRMWARE_VERSION_MAJOR=" in flag_str:
        version_major = flag_str.split("=")[-1]
    elif "FIRMWARE_VERSION_MINOR=" in flag_str:
        version_minor = flag_str.split("=")[-1]
    elif "FIRMWARE_VERSION_PATCH=" in flag_str:
        version_patch = flag_str.split("=")[-1]

# Also check CPPDEFINES which may be tuples
for define in env.get("CPPDEFINES", []):
    if isinstance(define, tuple) or isinstance(define, list):
        key, value = define[0], str(define[1])
        if key == "FIRMWARE_VERSION_MAJOR":
            version_major = value
        elif key == "FIRMWARE_VERSION_MINOR":
            version_minor = value
        elif key == "FIRMWARE_VERSION_PATCH":
            version_patch = value

version_string = f"{version_major}.{version_minor}.{version_patch}"

# Get git hash
try:
    git_hash = subprocess.check_output(
        ["git", "rev-parse", "--short", "HEAD"],
        stderr=subprocess.DEVNULL
    ).decode("utf-8").strip()
except (subprocess.CalledProcessError, FileNotFoundError):
    git_hash = "unknown"

# Build timestamps
build_unix = int(time.time())
build_date = time.strftime("%b %d %Y")
build_time = time.strftime("%H:%M:%S")
build_timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

# Full version string: <semver>-<unix_ts>. Format mirrors
# firmware/rp2040/cmake/GenerateVersion.cmake — NO git hash in between.
# The node-side extract_version_timestamp parses digits after the first
# dash; if a git hash sits in that slot it reads a partial integer and
# every up-to-date / OTA-comparison check produces wrong answers
# (server_ts of 276 vs current_ts of 1780175695 etc). Git hash stays
# available as the separate FIRMWARE_GIT_HASH define for diagnostics.
version_full = f"{version_string}-{build_unix}"

# Generate header
header_content = f"""/**
 * version.h - Auto-generated by generate_version.py
 *
 * DO NOT EDIT - this file is regenerated on every build.
 */

#ifndef VERSION_H
#define VERSION_H

#define FIRMWARE_VERSION_MAJOR   {version_major}
#define FIRMWARE_VERSION_MINOR   {version_minor}
#define FIRMWARE_VERSION_PATCH   {version_patch}
#define FIRMWARE_VERSION_STRING  "{version_string}"

#define FIRMWARE_BUILD_DATE      "{build_date}"
#define FIRMWARE_BUILD_TIME      "{build_time}"
#define FIRMWARE_BUILD_TIMESTAMP "{build_timestamp}"
#define FIRMWARE_BUILD_UNIX      {build_unix}

#define FIRMWARE_GIT_HASH        "{git_hash}"
#define FIRMWARE_VERSION_FULL    "{version_full}"

#define HARDWARE_MODEL           "Teensy 4.1"

#endif /* VERSION_H */
"""

# Write to include/version.h
include_dir = os.path.join(env.get("PROJECT_DIR", "."), "include")
os.makedirs(include_dir, exist_ok=True)
header_path = os.path.join(include_dir, "version.h")

# Always regenerate so timestamps are current
with open(header_path, "w") as f:
    f.write(header_content)

print(f"Generated {header_path} (v{version_full})")
